[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x', 'yarn']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT'