services:
  - name: acta-diurna
    type: web
    env: docker
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

databases:
  # MongoDB Atlas connection (external)
  # Configure MONGO_URL environment variable to point to your MongoDB Atlas cluster